### PR TITLE
Walmart is quietly preparing to enter the metaverse

### PR DESCRIPTION
**Pull request by Maya-Gonzalez**
[https://www.cnbc.com/amp/2022/01/16/walmart-is-quietly-preparing-to-enter-the-metaverse.html](url)

### CODE REVIEW

**Comment by justinnhli** [comment]
1. Please add your link to README.md instead of to a new file.
2. Please follow the markdown format of a bulletpoint with the link, and the summary underneath.

Tag me when you're ready for me to try merging again.

**Comment by Maya-Gonzalez** [comment]
@justinnhli I think this should be ready!

**Comment by justinnhli** [comment]
@Maya-Gonzalez The formatting is still off, and they need to be in README.md instead of in different files. Let me know if you're having trouble with this?

**Comment by Maya-Gonzalez** [comment]
Week 1 should be ready

**Pull request merged**
